### ISSUE TITLE
generate_meta_features.m has error 

### ISSUE THREAD

**Issue by attaullah** [duncan-barrack/kaggle_BCI_challenge#1]
there is error in file above mentioned, I am using Cotave 4 on ubuntu 15.10:

error: 'cell2table' undefined near line 23 column 16
error: called from
    generate_meta_features at line 23 column 15

**Comment by duncan-barrack** [comment]
Hi Attaullah,

Thanks for your comment. I haven't tested my code on Octave, only in Matlab. I suspect that Octave doesn't support the table data type and this is why you are getting this error. If you try the code in Matlab it should work.

Cheers,

Duncan
